# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nospoko
company_name: Nospoko
email: nospoko@nospoko.com
description: > # this means to ignore newlines until "baseurl:"
  Nospoko offers programming services in the field of non-trivial
  analytic problems using machine learning and fast fourier transform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nospoko.com" # the base hostname & protocol for your site

exclude: [vendor, ci, deploy_key.enc, Gemfile, Gemfile.lock]

gems:
  - jekyll-assets

# Build settings
markdown: kramdown

assets:
  prefix: "/assets"
  digest: true
  sources:
    - _assets/img
    - _assets/scss
    - _assets/js
    - _assets/fonts
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
